export const SET_LOADING_STATE = 'SET_AUTO_SCROBBLES_LOADING_STATE';
export const SET_ERROR_STATE = 'SET_AUTO_SCROBBLES_ERROR_STATE';
export const RECEIVED_AUTO_SCROBBLES = 'RECEIVED_AUTO_SCROBBLES';
export const START_DELETING = 'START_DELETING_AUTO_SCROBBLE';
export const END_DELETING = 'END_DELETING_AUTO_SCROBBLE';
export const REMOVE_AUTO_SCROBBLE = 'REMOVE_AUTO_SCROBBLE';
