export const SET_LOADING_STATE = 'SET_QUERY_LOADING_STATE';
export const SET_ERROR_STATE = 'SET_QUERY_ERROR_STATE';
export const SET_QUERY_STRING = 'SET_QUERY_STRING';
export const RECEIVED_RESULTS = 'RECEIVED_QUERY_RESULTS';
